### ISSUE TITLE
Typo on slide common script commands

### ISSUE THREAD

**Issue by BIMseven** [laboon/CS1699_Fall2018#11]
Lecture 8 slide 'common script commands' 
Op_checksig

**Comment by laboon** [comment]
Technically someone else got this first (and I fixed it in commit 3aedafed89ce0be8628cfa7aee3ffef8917e3dbb) but I'll give you +0.1 bonus anyway if you let me know your real name (either here or via email)

**Comment by laboon** [comment]
Based on username, I assume this is Ben Miller but let me know if not.

**Comment by BIMseven** [comment]
Yessir, that’s me. Thanks for the credit!

Benjamin Miller
University of Pittsburgh
(610)-772-6114

________________________________
