### ISSUE TITLE
Typo on Lecture 3 Slide 17

### ISSUE THREAD

**Issue by RamIyer1998** [laboon/CS1699_Fall2018#12]
The slide says:
"Given two pairs m/nonce and m’/nonce’, it is infeasible to find
m != m’ and commit(m, nonce) == commit(m, nonce)"

I believe this should say "commit(m,nonce) == commit(m’, nonce)" or "commit(m,nonce) == commit(m’, nonce’)"

**Comment by laboon** [comment]
Thank you, this was a major typo. Fixed in commit 66d5be2

+0.5 extra credit
