### ISSUE TITLE
Typo on Lecture08_Mechanics_of_Bitcoin.pdf

### ISSUE THREAD

**Issue by coltonb** [laboon/CS1699_Fall2018#15]
[On the slide titled "Outputs Must Be Entirely Consumed,"](https://github.com/laboon/CS1699_Fall2018/blob/master/lectures/Lecture08_Mechanics_of_Bitcoin.pdf) the transaction is invalid on block 3. It incorrectly states she sent 15 btc to Carol (the full amount in her "account") and received 10 btc back. As per the previous slide, Alice could have only sent Carol 5 btc to have 10 btc returned back.

Also, earlier in the slides you note for a given transaction the total outputs must be < than the inputs. Wouldn't it be <= ? This is a little pedantic though since the meaning is obvious.

Colton Blake

**Comment by laboon** [comment]
Yes, two significant typos.  Adding +0.8 to your extra credit score and will fix in a commit in a second...
