### ISSUE TITLE
Question regarding deliverable 1 ambiguity

### ISSUE THREAD

**Issue by coltonb** [laboon/CS1699_Fall2018#19]
On the deliverable instructions you write:

> Note: These are the public/private keys used in the sample blockchain files. However, they are not the ONLY possible public/private keypairs! You may create your own for testing purposes and the files that will be graded may contain other keypairs other than these. Your program should as function as long as the key pairs are valid!

Are we meant to include a method to provide for the case that Bill's keys are different than those listed on the deliverable, or are we safe to assume they are constant?

**Comment by laboon** [comment]
Bill's keys will never be different, he (and his specified keypair) will ALWAYS be the only ones that can create coins.

I sent out an email to the class to clarify since others have asked me this privately.  I will give you +0.25 for being the first to post the issue publicly.

**Comment by coltonb** [comment]
Thanks! I figured this was likely the case.
