### ISSUE TITLE
Misspelling of "Cryptocurrency in syllabus"

### ISSUE THREAD

**Issue by EricGhildyal** [laboon/CS1699_Fall2018#2]
On [this page](https://github.com/laboon/CS1699_Fall2018/blob/master/syllabus.md) cryptocurrency is misspelled.

It says: 
`CS1699 Special Topics: Blockchain Technology and Cryptocurreny`

It should be: 
`CS1699 Special Topics: Blockchain Technology and Cryptocurrency`

**Comment by laboon** [comment]
Thanks, fixed in commit 30ca757793e21d1b871d711ea9ae8ec0fa202e29

Added +0.1 bonus to your final grade
