### ISSUE TITLE
Deliverable 1 Issue Regarding Wording

### ISSUE THREAD

**Issue by zaxway12** [laboon/CS1699_Fall2018#20]
This is a rather trivial issue or rather question perhaps, but on deliverable 1, you mentioned the following line at the very end of the "StringCoin blockchain format" section: 

This should be sorted by coin ID alphabetically.

The problem is all coin IDs are numeric in our program. Do we have to assume that they could be alphabetical/alpha-numeric as well, and sort them as such?

**Comment by laboon** [comment]
The coin IDs are numeric but can still be sorted "ASCII-betically".  I will be creating all coins "in order" so you could also just make sure they are printed out in the same order they are created.
