### ISSUE TITLE
Attacks on a mining pool

### ISSUE THREAD

**Issue by rubenhorn** [laboon/CS1699_Fall2018#27]
During the lecture today I asked what would keep a member of a mining pool from withholding the correct nonce from the pool and instead submitting the block themselves to earn the full reward and fees.

Bitcoin uses the [getblocktemplate](https://en.bitcoin.it/wiki/Getblocktemplate) protocol.
Even though, as opposed to the old getwork protocol, pool members don't only get the block header from the administrator, they still cannot "steal" the block, since changing the coinbase transaction would also change the Merkle root and the resulting hash.
It is thus not easier to exploid a pool in that way than it is to mine alone.

However it is possible to withhold the correct nonce and continue submitting near misses.
(More on BWH attacks in [this paper](https://link.springer.com/chapter/10.1007/978-3-319-45871-7_11))

**Comment by laboon** [comment]
Of course it will change the Merkle root!  Can't believe I wasn't able to answer this well in class.  Getting old I guess.  +1 EC
