### ISSUE TITLE
Lecture 3 - slide 19

### ISSUE THREAD

**Issue by kirtansakariya** [laboon/CS1699_Fall2018#3]
In lecture 3, slide 19, for the first bullet, instead of this statement:
In other words, if someone wants the hash value result H(x) to be a particular value y, if H(x) produces a result of size n bits, then finding H(x) should require at least 2<sup>n</sup> attempts ( O(2<sup>n</sup>) )

Should the last H(x) be changed to just an x? Resulting in this:
In other words, if someone wants the hash value result H(x) to be a particular value y, if H(x) produces a result of size n bits, then finding **x** should require at least 2<sup>n</sup> attempts ( O(2<sup>n</sup>) )

**Comment by laboon** [comment]
Yes, this is a typo, although it is "kind of" still right.  What I was trying to say is that are looking for a particular value of H(x) such that H(x) == y.  There should be no better way of producing H(x) == y other than trying different values of x.  So yes, even though our real "goal" is finding H(x) == y the best way to actually find the correct value of H(x) *is* by just finding a correct value for x.

So while it's not _really_ incorrect, the slide does not explain it as the book does and it is thus confusing.  I have updated the slide in commit 1b140b199150960a4ff4ba885448b9acf7d17717 and given you +0.5 bonus points for bringing this to my attention.
