### ISSUE TITLE
[Deliverable 2] Transaction hashes

### ISSUE THREAD

**Issue by zacyu** [laboon/CS1699_Fall2018#30]
In the [requirement doc](https://github.com/laboon/CS1699_Fall2018/blob/master/deliverables/2/deliverable2.md) for deliverable 2, under section section **Valid Block and Output**, the expected components for the block output is specified. Part 7 (list of transactions) mentions that each transaction output consists of transaction inputs, transaction outputs, and hash of transaction.

The hash of a transaction, however, is not defined for BillCoin. And none of the sample outputs provided in the doc includes such component; instead, the format from the input file (candidate_transaction_file) is used.

Could you please clarify the output format for the list of transactions?

**Comment by laboon** [comment]
The inclusion of the hash of each transaction was a holdover from the previous iteration of the assignment.  You should not calculate or include the hash of each transaction and output should appear in the same format as from the sample input file as shown.

Thank you for catching.  I have modified the deliverable2.md file in the commit mentioned above to specify only input/output tx's.

+1 EC
