### ISSUE TITLE
Deliverable-2 Comparing Hash

### ISSUE THREAD

**Issue by michaelhoesch** [laboon/CS1699_Fall2018#36]
For the program to succeed, are we supposed to compare the block hash calculated to the target difficulty calculated, like in the Miner.java example in sample code, or compare the block hash calculated to the previous hash?  It just looks weird where the valid candidate block hash is greater than the previous hash when you output the results.

**Comment by laboon** [comment]
It should compare only to the difficulty being passed in.  You should ignore the previous hash in terms of difficulty.

It may look weird, but it's not unprecedented - difficulty in Bitcoin can (and does) go up or down depending on the hashpower of the network over the preceding 2016 blocks.

It's also possible that even though the previous hash was very small (e.g., 0x000000000000000000000001), the difficulty was also small and so the target was something like 0x000FFFFFFFFFFFFFFFFFFFFFFF), it's just that the miner found a very small hash result (which would still be valid!)

**Comment by michaelhoesch** [comment]
Understood. Thank you!
