### ISSUE TITLE
PoUW Coins

### ISSUE THREAD

**Issue by minj131** [laboon/CS1699_Fall2018#44]
**Gridcoin:**
https://www.gridcoin.us/

**Qarnot**
https://www.qarnot.com/crypto-heater_qc1/

**Permacoin**
https://www.microsoft.com/en-us/research/publication/permacoin-repurposing-bitcoin-work-for-data-preservation/

**Comment by laboon** [comment]
gridcoin actually uses PoS to secure itself -  even though the side effect is useful, it's not proof of useful work

Qarnot - this just uses the leftover heat as a heater, doesn't seem like the computation itself is useful?

Permacoin - this is proof-of-storage as discussed in class

I'll give +0.1 for the examples though...
