### ISSUE TITLE
Proof-of-Useful Work Coins

### ISSUE THREAD

**Issue by NohrianScum** [laboon/CS1699_Fall2018#45]
Would AlienCoin count as a sort of PoUW Coin? https://aliencoin.space/

**Comment by laboon** [comment]
Ehh, I wouldn't consider it a pure PoUW work coin because if you read the whitepaper, they have to manually give out ERC-20 tokens based on screenshots - this is a bit of a hack!  But I'll give you +0.1 EC for finding it.
