### ISSUE TITLE
NooShare: Proof of useful work

### ISSUE THREAD

**Issue by KrithikaGanesh** [laboon/CS1699_Fall2018#47]
http://web.mit.edu/alex_c/www/nooshare.pdf
**Changing the hashing function to do a useful computation:** 
"NooShare transactions which can schedule computation
of arbitrary Monte Carlo functions in the proof-of-work lottery."

**Comment by laboon** [comment]
This is another instance of a proposal that was not actually implemented in a used coin.  Interesting but not what I was looking for...
