### ISSUE TITLE
Practical Non-outsourceable puzzle: BlockPoW

### ISSUE THREAD

**Issue by KrithikaGanesh** [laboon/CS1699_Fall2018#48]
https://bitslog.wordpress.com/2014/06/19/theoretical-and-practical-nonoutsourceable-puzzles/

"The idea is that if miners try to join a pool, then they incur in overhead and earn less than working solo."

**Comment by laboon** [comment]
Krithika - Yes, there are known non-outsourceable proposals but I was looking for actual implementations in real coins using this.
