### ISSUE TITLE
Lecture 17 Smart Property

### ISSUE THREAD

**Issue by eca20** [laboon/CS1699_Fall2018#52]
"Now provides perfect traceability" - does the idea of "smart property" make it tougher or easier for a person to hide property/assets from an entity like the IRS. Or from the other angle, does it make it tougher or easier for an entity like the IRS to trace ownership of property.

**Comment by laboon** [comment]
We covered this in class I believe.  It makes their job much easier assuming a link to a real-world identity using Civic or similar. https://www.civic.com/company/

+0.5 EC
