### ISSUE TITLE
Lecture 10: Possible Secret Sharing Typo

### ISSUE THREAD

**Issue by paranoidandroid81** [laboon/CS1699_Fall2018#54]
Hi:

On the slide in Lecture 10 called "Arbitrary k-of-n Secret Sharing" it says that for k-of-n secret sharing, we can derive a "k-order polynomial" so that having k points on the line will reveal the secret on the y-intercept. However, it appears that this should be a "k-1" order polynomial as indicated by the book and the fact that on the previous slide for k=3 we used a parabola or polynomial with an order of 2.

Thanks,
Michael Korst

**Comment by laboon** [comment]
Ugh yes this was a bad typo!  I have given you +1 EC as this was a significant mathematical error on my part.
