### ISSUE TITLE
Lecture 10 typo on Base58Check Encoding Slide

### ISSUE THREAD

**Issue by eca20** [laboon/CS1699_Fall2018#57]
"Note that 0 (capital O), 0 (zero)... and I (capital i) to avoid confusion. " - the sentence is not completed.

**Comment by laboon** [comment]
Do you mean on slide 4?  This is what I see, which looks like a complete sentence to me..

<img width="1238" alt="screen shot 2018-11-06 at 1 48 23 pm" src="https://user-images.githubusercontent.com/1417717/48086375-b91b0800-e1ca-11e8-87cd-9a3df763d174.png">

**Comment by eca20** [comment]
I just realized, I was looking at a much older version of the slides while studying this morning, so the issue was probably noticed and already fixed weeks ago.

Thanks!
Ed

**Comment by laboon** [comment]
Closing this issue as it seems to have been a misunderstanding.  Feel free to re-open if not.
