### ISSUE TITLE
Deliverable 3 -ultraverbose output

### ISSUE THREAD

**Issue by rym23** [laboon/CS1699_Fall2018#59]
Right before you print the initial array in the -ultraverbose output, I see that you run LaboonHash on the last element of the 2-d array, "6A82", and get a result of "1A97".  This value is never used, so does the last value need to be hashed & printed?

**Comment by laboon** [comment]
Ahh, no, just an off-by-one error!  It does not need to be printed. Assuming your GitHub username matches your Pitt username, I have given you +0.3 EC.
