### ISSUE TITLE
Deliverable 3 Part 1: LaboonHash typo

### ISSUE THREAD

**Issue by lje7600** [laboon/CS1699_Fall2018#61]
Hi Professor Laboon,
there might be a typo in # '9' description of Deliverable 3 Part 1: LaboonHash.

Here is the line #9 description of part 1:
... Rather, you should take the length modulo n ^ 16 where n is the number of spaces available...

According to your example code, I would assume that it is '16 ^ n', instead of 'n ^ 16' ..?
The formula is described as '16 ^ n' in Strengthening Description and Example followed by part 1.

**Comment by laboon** [comment]
!!! Definitely a typo.  It's 16^n (as I mention later in the Strengthening Description section)

What is your real name?  Feel free to email it to me if you do not want it associated with your GitHub handle, you will get +0.5 extra credit.

**Comment by laboon** [comment]
Ahh actually I see your username on one of your assignments.  I will add your extra credit to courseweb now.

**Comment by lje7600** [comment]
okay, sounds great.
Thank you! :)
