### ISSUE TITLE
[Deliverable 3] Use of Sample Code

### ISSUE THREAD

**Issue by coltonb** [laboon/CS1699_Fall2018#65]
I used two of your methods from the Merkle-Damgard Strengthening sample code for this assignment (for string splitting and padding) as I assumed this was acceptable; however, I notice now that you don't mention that it is okay to use your sample code in this deliverable as was the case with the others. I am going to guess that you meant to specify that doing so was okay, but please let me know!

**Comment by laboon** [comment]
Yes, this is fine.  I just forgot to write it.  I'll add it now and add +0.3 extra credit for you for noticing it.
