### ISSUE TITLE
[Deliverable 3] Merkle-Damgard transform/strengthening on empty string

### ISSUE THREAD

**Issue by zacyu** [laboon/CS1699_Fall2018#71]
Thanks for updating the [grading_rubric](https://github.com/laboon/CS1699_Fall2018/blob/1f6cd431de55900fe5bc6f46ecde00583f10382d/deliverables/3/grading_rubric.txt) for deliverable 3.

I noticed that the excepted output for the empty string on LaboonHash is `1AB0`, namely the value of the initialization vector. Similarly, the excepted output for the empty string on LaboonCrypt is `5BBF`, produced directly from having `1AB0` at the initial location of the matrix. In other words, Merkle-Damgard transform/strengthening treats the empty string as zero block and does not add padding and length to it; as a result, the initialization vector is left untouched.

This behevior differs from that of commonly used Merkle-Damgard hash functions, where an input of null or empty string is treated as one block with length 0 and then padded to the block size. I further observed that the [sample code](https://github.com/laboon/CS1699_Fall2018/blob/bdd19b70f219d43feb8951181241750e491d8deb/sample_code/merkle_damgard_transform/LaboonHash.java) provided for Merkle-Damgard transform *does* pad empty string to a full block as well.

In my implementation of deliverable 3, the empty string input is padded, resulting in a LaboonHash hash of `1311` and a LaboonCrypt hash of `D62C`, as shown below:

```
> java LaboonHash "" -verbose
	Padded string: 00000000
	Blocks:
	00000000
	Iterating with 1AB0 / 00000000 = 1311
	Final result: 1311
LaboonHash hash = 1311

> java LaboonCrypt "" -verbose
Initial array:
1311 7726 4A33 4740 1C55 3362 4277 8C8C 8C90 DFA5 6A22 1037
D64C 4D50 1065 3572 4F87 819C 89A0 D925 6832 1E47 D25C 4260
1375 3D82 4F97 82AC 8620 DB35 6042 1757 DF6C 4F70 1085 3B92
4EA7 852C 8430 D245 6152 1567 D07C 4A80 1A95 39A2 4927 883C
8E40 D255 6262 1377 DD8C 4F90 12A5 3622 4B37 804C 8750 DF65
6F72 1087 DB9C 4EA0 1525 3432 4247 815C 8560 D075 6A82 1A97
D9AC 4920 1835 3E42 4257 826C 8370 DD85 6F92 12A7 D62C 4B30
1045 3752 4F67 8F7C 8080 DB95 6EA2 1527 D43C 4240 1155 3562
4077 8A8C 8A90 D9A5 6922 1837 DE4C 4250 1265 3372 4D87 8F9C
82A0 D625 6B32 1047 D75C 4F60 1F75 3082 4B97 8EAC 8520 D435
6242 1157 D56C 4070 1A85 3A92 49A7 892C 8830 DE45 6252 1267
D37C 4D80 1F95 32A2 4627 8B3C 8040 D755 6F62 1F77 D08C 4B90
Final array:
1311 7726 4A33 4740 1C55 3362 4277 8C8C 8C90 DFA5 6A22 1037
D64C 4D50 1065 3572 4F87 819C 89A0 D925 6832 1E47 D25C 4260
1375 3D82 4F97 82AC 8620 DB35 6042 1757 DF6C 4F70 1085 3B92
4EA7 852C 8430 D245 6152 1567 D07C 4A80 1A95 39A2 4927 883C
8E40 D255 6262 1377 DD8C 4F90 12A5 3622 4B37 804C 8750 DF65
6F72 1087 DB9C 4EA0 1525 3432 4247 815C 8560 D075 6A82 1A97
D9AC 4920 1835 3E42 4257 826C 8370 DD85 6F92 12A7 D62C 4B30
1045 3752 4F67 8F7C 8080 DB95 6EA2 1527 D43C 4240 1155 3562
4077 8A8C 8A90 D9A5 6922 1837 DE4C 4250 1265 3372 4D87 8F9C
82A0 D625 6B32 1047 D75C 4F60 1F75 3082 4B97 8EAC 8520 D435
6242 1157 D56C 4070 1A85 3A92 49A7 892C 8830 DE45 6252 1267
D37C 4D80 1F95 32A2 4627 8B3C 8040 D755 6F62 1F77 D08C 4B90
LaboonCrypt hash: D62C
```

Note that modification is perform in the case of LaboonCrypt since the input string is empty.

As I couldn't find any instructions regarding the handling of empty strings in the [requirement doc](https://github.com/laboon/CS1699_Fall2018/blob/2dc5e6c86a6445dd7f0ea3dc3e9b62167bca68de/deliverables/3/deliverable3.md) or in the lecture slidedecks, I am wondering if the behavior I implemented is expected, and if my outputs can also be accepted as correct answers.

**Comment by laboon** [comment]
This was an error in my sample code for this edge case.  I have updated the grading rubric to make both acceptable.

I will add +1 EC for finding a significant error as soon as I can log in to courseweb (will probably be tomorrow).
