### ISSUE TITLE
Typo in Lecture 8

### ISSUE THREAD

**Issue by Bin-Dong** [laboon/CS1699_Fall2018#9]
Transaction Based Ledgar slide (the slide before Verification only back until coin creation)
There is a typo for block 3. If Alice has 25 coins, send 10 coins to Bob and send 15 to Carol, Alice should not have 10 coins send back to her.

**Comment by laboon** [comment]
Fixed in commit 3aedafed89ce0be8628cfa7aee3ffef8917e3dbb, added +0.3 bonus
